### ISSUE TITLE
Drag event on Chrome 72

### ISSUE THREAD

**Issue by anbi** [d3/d3-drag#58]
In last release Chrome 72, d3 drag doesn't fire "drag" event, but "start" and "end" still working.

**Comment by mbostock** [comment]
I’m not able to reproduce this error.

When reporting an issue, please include a link to a live example, preferably as an [Observable notebook](https://beta.observablehq.com) or as a pull request in the [appropriate repository](https://github.com/d3) with tests. You should demonstrate that the described behavior is not the [expected behavior](https://github.com/d3/d3/blob/master/API.md) using the minimum amount of code.

A good bug report should **isolate specific methods** that exhibit unexpected behavior and define precisely how expectations were violated. What did you expect the method or methods to do, and how did the observed behavior differ? By isolating the issue, you assist the investigation.

Non-actionable bugs may be closed until you provide additional information. If you can’t isolate the bug further, please reply and ask for help. However, please be patient: open-source maintainers have many competing responsibilities—fixing other bugs, answering questions, developing features, writing documentation, *etc.* Please also consider asking for help on [Stack Overflow](https://stackoverflow.com/tags/d3.js).

If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗

**Comment by anbi** [comment]
@mbostock sorry for short request. 
Later i'll try to explain the problem with live code (now is reserved).

We have use this workaround for force to trigger the event: 

`document.addEventListener("touchstart", function( event ) {
			console.log('hi')
}, false);`

Thanks. 😉

**Comment by mbostock** [comment]
See #47.
